// @uportal/esco-content-menu-lit/src/content-menu.ts
/*Lit*/
import { html, LitElement, css, unsafeCSS, TemplateResult } from 'lit';
import { customElement, property, state } from 'lit/decorators.js';
import { classMap } from 'lit/directives/class-map.js';
import { styleMap } from 'lit/directives/style-map.js';
/*SCSS*/
import ContentMenuScss from '@styles/content-menu.scss';
/*Mixins*/
import { LitLoggable } from '@mixins/litLoggable';
/*Services*/
import portletService from '@services/portletService';
import favoritesService from '@services/favoritesService';
import OrganizationService from '@services/organizationService';
/*Helpers*/
import sizeHelper from '@helpers/sizeHelper';
/*Components*/
import './content-user';
import './content-favorites';
import './content-grid';
import './header-buttons';
import './lit-spinner';

@customElement('esco-content-menu')
export class ContentMenu extends LitLoggable(LitElement) {
  @property({ type: Array })
  messages = [];
  @property({
    type: String,
    hasChanged(newVal: string) {
      return sizeHelper.validate(newVal, true, true);
    },
    attribute: 'favorites-Portlet-card-size',
  })
  favoritesPortletCardSize = 'small';
  @property({
    type: String,
    hasChanged(newVal: string) {
      return sizeHelper.validate(newVal, true, true);
    },
    attribute: 'grid-Portlet-card-size',
  })
  gridPortletCardSize = 'auto';
  @property({ type: String, attribute: 'default-org-logo' })
  defaultOrgLogo = '';
  @property({ type: String, attribute: 'force-org-logo' })
  forceOrgLogo = '';
  @property({ type: String, attribute: 'context-api-url' })
  contextApiUrl = process.env.APP_PORTAL_CONTEXT ?? '';
  @property({ type: String, attribute: 'favorite-api-url' })
  favoriteApiUrl =
    (process.env.APP_PORTAL_CONTEXT ?? '') +
    (process.env.APP_FAVORITES_PORTLETS_URI ?? '');
  @property({ type: String, attribute: 'layout-api-url' })
  layoutApiUrl =
    (process.env.APP_PORTAL_CONTEXT ?? '') +
    (process.env.APP_FAVORITES_URI ?? '');
  @property({ type: String, attribute: 'portlet-api-url' })
  portletApiUrl =
    (process.env.APP_PORTAL_CONTEXT ?? '') +
    (process.env.APP_BROWSABLE_PORTLETS_URI ?? '');
  @property({ type: String, attribute: 'organization-api-url' })
  organizationApiUrl = '';
  @property({ type: String, attribute: 'user-info-api-url' })
  userInfoApiUrl =
    (process.env.APP_PORTAL_CONTEXT ?? '') +
    (process.env.APP_USER_INFO_URI ?? '');
  @property({ type: String, attribute: 'sign-out-url' })
  signoutUrl = process.env.APP_LOGOUT_URL;
  @property({ type: String, attribute: 'user-info-portlet-url' })
  userInfoPortletUrl = '';
  @property({ type: String, attribute: 'switch-org-portlet-url' })
  switchOrgPortletUrl = '';
  @property({ type: String, attribute: 'user-org-id-attribute-name' })
  orgAttributeName = 'ESCOSIRENCourant[0]';
  @property({ type: String, attribute: 'org-logo-url-attribute-name' })
  orgLogoUrlAttributeName = 'otherAttributes.ESCOStructureLogo[0]';
  @property({ type: String, attribute: 'user-all-orgs-id-attribute-name' })
  userAllOrgsIdAttributeName = 'ESCOSIREN';
  @property({ type: String, attribute: 'card-hover-src' })
  cardHoverSrc = 'none';
  @property({
    type: String,
    hasChanged(newVal: string) {
      return ['auto', 'always', 'never'].includes(newVal);
    },
    attribute: 'hide-action-mode',
  })
  hideActionMode = 'auto';
  @property({ type: Boolean, attribute: 'is-hidden' })
  isHidden = false;
  @property({ type: Boolean, attribute: 'show-favorites-in-slider' })
  showFavoritesInSlider = false;
  @property({ type: Boolean })
  debug = false;
  @property({ type: Boolean, attribute: 'fake-attribute' })
  fakeAttribute = false;

  @state()
  _screenSize = 'medium';
  @state()
  _hideAction = false;
  @state()
  _currentOrg: Organization | null = null;
  @state()
  _currentUser: UserInfo | null = null;
  @state()
  _currentUserOrgs: OrgInfo | null = null;
  @state()
  _portlets: Portlet[] | null = null;
  @state()
  _favorites: string[] | null = null;

  constructor() {
    super();
    this.debugLog('Component loaded');
  }

  connectedCallback(): void {
    super.connectedCallback();
    window.addEventListener('resize', this.calculateSize.bind(this));
  }

  disconnectedCallback(): void {
    super.disconnectedCallback();
    window.removeEventListener('resize', this.calculateSize.bind(this));
  }

  shouldUpdate(): boolean {
    if (this.defaultOrgLogo === '') {
      this.errorLog('default-org-logo attribute is required');
      return false;
    }
    return true;
  }

  updated(changedProperties: Map<string | number | symbol, unknown>): void {
    if (changedProperties.has('userInfoApiUrl')) {
      if (changedProperties.has('portletApiUrl')) {
        if (!this._portlets) this.fetchPortlets();
      }
      if (changedProperties.has('layoutApiUrl')) {
        if (!this._favorites) this.fetchFavorites();
      }
      if (
        changedProperties.has('organizationApiUrl') ||
        changedProperties.has('userAllOrgsIdAttributeName')
      ) {
        this.fetchUserInfo();
      }
    }

    if (changedProperties.has('isHidden')) {
      this.calculateSize();
    }
  }

  async fetchPortlets(): Promise<void> {
    const portlets = await portletService.fetch(
      this.userInfoApiUrl,
      this.portletApiUrl,
      this.debug
    );
    if (portlets) {
      this._portlets = portletService
        .portletRegistryToArray(portlets)
        .sort(portletService.sortPortlets);
    } else {
      this.errorLog('No portlets fetch from API');
    }
  }
  async fetchFavorites(): Promise<void> {
    const favoritesTree = await favoritesService.fetch(
      this.userInfoApiUrl,
      this.layoutApiUrl,
      this.debug
    );
    if (favoritesTree) {
      this._favorites = favoritesService.flattenFavorites(favoritesTree);
    }
  }
  async fetchUserInfo(): Promise<void> {
    const fetchResult = await OrganizationService.fetch(
      this.userInfoApiUrl,
      this.organizationApiUrl,
      this.userAllOrgsIdAttributeName,
      this.debug
    );
    if (fetchResult) {
      this.debugLog('userInfo API result', fetchResult);
      this._currentUser = fetchResult?.user as UserInfo;
      this._currentUserOrgs = fetchResult?.organizations as OrgInfo;
      if (this._currentUser && this._currentUserOrgs)
        this._currentOrg = OrganizationService.getCurrentOrganization(
          this._currentUser,
          this.userAllOrgsIdAttributeName,
          this._currentUserOrgs
        );
    } else {
      this.errorLog('No user infos fetch from API');
    }
  }

  calculateSize(): void {
    if (this.isHidden) return;
    this._screenSize = sizeHelper.breakPointName(
      sizeHelper.elementWidth(this.shadowRoot?.querySelector('#content-menu'))
    );
    this.debugLog(
      'calculateSize',
      this.shadowRoot?.querySelector('#content-menu')
    );
    switch (this.hideActionMode) {
      case 'auto':
        this._hideAction =
          this._screenSize === 'small' || this._screenSize === 'smaller';
        break;
      case 'never':
        this._hideAction = false;
        break;
      default:
        // case of 'always' hidden
        this._hideAction = true;
    }
    this.debugLog('calculateSize', this._screenSize);
  }

  onClose(e: Event): void {
    e.preventDefault();
    const closeEvt = new CustomEvent('close');
    this.dispatchEvent(closeEvt);
  }

  isOtherOrgs(): boolean {
    return (
      (this._currentUserOrgs &&
        Object.keys(this._currentUserOrgs).length > 1) ??
      false
    );
  }

  getOrgImage(): string {
    return (
      this.forceOrgLogo ||
      OrganizationService.getOrganizationLogo(
        this._currentOrg,
        this.orgLogoUrlAttributeName
      ) ||
      this.defaultOrgLogo
    );
  }

  actionToggleFav(e: CustomEvent): void {
    if (!this._favorites) this._favorites = [];
    if (!this._favorites.includes(e.detail.fname)) {
      this._favorites = [...this._favorites, e.detail.fname];
    } else {
      this._favorites = this._favorites.filter(
        (name) => name != e.detail.fname
      );
    }
    if (!this.debug && e.detail?.chanId !== undefined) {
      if (e.detail?.isFavorite) {
        favoritesService.add(
          this.userInfoApiUrl,
          this.favoriteApiUrl,
          e.detail.chanId
        );
      } else {
        favoritesService.remove(
          this.userInfoApiUrl,
          this.favoriteApiUrl,
          e.detail.chanId
        );
      }
    }
  }

  render(): TemplateResult {
    this.debugLog('Render');
    const headerBGImg =
      'linear-gradient(0deg, rgba(0,0,0,.2),rgba(0,0,0,.2)), url(' +
      this.getOrgImage() +
      ');';
    return this._portlets && this._favorites
      ? html`
          <div
            id="content-menu"
            class="content-menu toggler-menu ${classMap({
              [this._screenSize]: true,
              'active-menu': !this.isHidden,
            })}"
          >
            <header>
              <div id="header-buttons">
                <slot name="header-buttons">
                  <esco-header-buttons
                    .messages=${this.messages}
                    sign-out-url="${this.signoutUrl ?? ''}"
                    @close=${this.onClose}
                  ></esco-header-buttons>
                </slot>
              </div>

              <div class="wrapper">
                <slot name="content-user">
                  <esco-content-user
                    .messages=${this.messages}
                    parent-screen-size="${this._screenSize}"
                    user-display-name="${this._currentUser?.name ?? ''}"
                    user-avatar-url="${this._currentUser?.picture ?? ''}"
                    org-display-name="${this._currentOrg?.displayName ?? ''}"
                    org-img-url="${this.getOrgImage()}"
                    user-info-portlet-url="${this.userInfoPortletUrl}"
                    switch-org-portlet-url="${this.isOtherOrgs()
                      ? this.switchOrgPortletUrl
                      : ''}"
                  ></esco-content-user>
                </slot>
                <esco-content-favorites
                  .messages=${this.messages}
                  .portlets="${this._portlets as never[]}"
                  .favorites="${this._favorites as never[]}"
                  parent-screen-size="${this._screenSize}"
                  card-size="${this.favoritesPortletCardSize}"
                  ?hide-action="${this._hideAction}"
                  favorite-api-url="${this.favoriteApiUrl}"
                  ?hide="${this.isHidden}"
                  user-info-api-url="${this.userInfoApiUrl}"
                  context-api-url="${this.contextApiUrl}"
                  ?debug="${this.debug}"
                  ?disable-swiper="${!this.showFavoritesInSlider}"
                  @toggle-favorite=${this.actionToggleFav}
                ></esco-content-favorites>
              </div>
              <div
                style="${styleMap({ 'background-image': headerBGImg })}"
                class="background"
              ></div>
            </header>
            <esco-content-grid
              .messages=${this.messages}
              .portlets="${this._portlets as never[]}"
              .favorites="${this._favorites as never[]}"
              parent-screen-size="${this._screenSize}"
              portlet-card-size="${this.gridPortletCardSize}"
              ?hide-action="${this._hideAction}"
              favorite-api-url="${this.favoriteApiUrl}"
              layout-api-url="${this.layoutApiUrl}"
              user-info-api-url="${this.userInfoApiUrl}"
              context-api-url="${this.contextApiUrl}"
              portlet-api-url="${this.portletApiUrl}"
              card-hover-src="${this.cardHoverSrc}"
              ?debug="${this.debug}"
              @toggle-favorite=${this.actionToggleFav}
            ></esco-content-grid>
          </div>
        `
      : html`<div id="content-menu" class="content-menu spinner">
          <lit-spinner></lit-spinner>
        </div>`;
  }

  static styles = [
    css`
      ${unsafeCSS(ContentMenuScss)}
    `,
  ];
}

// @uportal/esco-content-menu/src/components/ContentMenu.vue
<template>
  <div
    :class="['toggler-menu', _screenSize, !_isHidden ? 'active-menu' : '']"
    class="content-menu"
  >
    <header>
      <slot name="header-buttons">
        <header-buttons :call-on-close="close" :sign-out-url="signOutUrl" />
      </slot>
      <div class="wrapper">
        <slot name="content-user">
          <content-user
            :org-info="_userOrganization"
            :user-info="_user"
            :other-orgs="_organizations"
            :parent-screen-size="_screenSize"
            :default-org-logo="defaultOrgLogo"
            :force-org-logo="forceOrgLogo"
            :user-info-portlet-url="userInfoPortletUrl"
            :switch-org-portlet-url="switchOrgPortletUrl"
            :org-logo-url-attribute-name="orgLogoUrlAttributeName"
          />
        </slot>
        <content-favorites
          :portlets="_portlets"
          :favorites="_favorites"
          :call-after-action="actionToggleFav"
          :parent-screen-size="_screenSize"
          :portlet-card-size="favoritesPortletCardSize"
          :hide-action="hideAction"
          :favorite-api-url="favoriteApiUrl"
          :is-hidden="_isHidden"
          :user-info-api-url="userInfoApiUrl"
          :context-api-url="contextApiUrl"
          :debug="debug"
          :use-swipper="showFavoritesInSlider"
        />
      </div>
      <div
        :style="
          getOrgImgUrl() != null &&
          (_screenSize === 'large' || _screenSize === 'medium')
            ? 'background-image: linear-gradient(0deg, rgba(0,0,0,.2),rgba(0,0,0,.2)), url(' +
              getOrgImgUrl() +
              ');'
            : ''
        "
        class="background"
      />
    </header>
    <content-grid
      :messages="messages"
      :portlets="_portlets"
      :favorites="_favorites"
      :call-after-action="actionToggleFav"
      :parent-screen-size="_screenSize"
      :portlet-card-size="gridPortletCardSize"
      :hide-action="hideAction"
      :favorite-api-url="favoriteApiUrl"
      :layout-api-url="layoutApiUrl"
      :user-info-api-url="userInfoApiUrl"
      :context-api-url="contextApiUrl"
      :portlet-api-url="portletApiUrl"
      :debug="debug"
    />
    <vue-simple-spinner
      v-show="isLoading"
      class="spinner"
      line-fg-color="#545454"
    />
  </div>
</template>

<script>
import ContentFavorites from './ContentFavorites';
import ContentGrid from './ContentGrid';
import ContentUser from './ContentUser';
import HeaderButtons from './HeaderButtons';
import vueSimpleSpinner from 'vue-simple-spinner';
import fetchUserInfoAndOrg from '../services/fetchUserInfoAndOrgs';
import fetchPortlets from '../services/fetchPortlets';
import fetchFavorites from '../services/fetchFavorites';
import { portletRegistryToArray } from '../services/portlet-registry-to-array';
import flattenFavorites from '../services/flattenFavorites';
import byPortlet from '../services/sortByPortlet';
import toggleArray from '../services/toggleArray';
import i18nMixin from '../mixins/i18n.js';
import {
  elementWidth,
  breakPointName,
  sizeValidator,
} from '../services/sizeTools';
import {
  getCurrentOrganization,
  getOrganizationLogo,
} from '../services/organizationHelper';
import computeUrl from '../services/computeUrl';

export default {
  name: 'ContentMenu',
  mixins: [i18nMixin],
  components: {
    ContentFavorites,
    ContentGrid,
    ContentUser,
    HeaderButtons,
    vueSimpleSpinner,
  },
  props: {
    id: { type: String, default: null },
    callOnClose: { type: Function, default: () => {} },
    isHidden: { type: Boolean, default: false },
    contextApiUrl: {
      type: String,
      default: process.env.VUE_APP_PORTAL_CONTEXT,
    },
    favoriteApiUrl: {
      type: String,
      default:
        process.env.VUE_APP_PORTAL_CONTEXT +
        process.env.VUE_APP_FAVORITES_PORTLETS_URI,
    },
    layoutApiUrl: {
      type: String,
      default:
        process.env.VUE_APP_PORTAL_CONTEXT + process.env.VUE_APP_FAVORITES_URI,
    },
    organizationApiUrl: {
      type: String,
      default: null,
    },
    portletApiUrl: {
      type: String,
      default:
        process.env.VUE_APP_PORTAL_CONTEXT +
        process.env.VUE_APP_BROWSABLE_PORTLETS_URI,
    },
    userInfoApiUrl: {
      type: String,
      default:
        process.env.VUE_APP_PORTAL_CONTEXT + process.env.VUE_APP_USER_INFO_URI,
    },
    debug: { type: Boolean, default: false },
    signOutUrl: { type: String, default: process.env.VUE_APP_LOGOUT_URL },
    defaultOrgLogo: { type: String, required: true },
    forceOrgLogo: { type: String },
    userInfoPortletUrl: { type: String, default: '' },
    switchOrgPortletUrl: { type: String, default: '' },
    favoritesPortletCardSize: {
      validator: (value) => sizeValidator(value, true),
      default: 'auto',
    },
    gridPortletCardSize: {
      validator: (value) => sizeValidator(value, true),
      default: 'auto',
    },
    hideActionMode: {
      validator: (value) => ['auto', 'always', 'never'].includes(value),
      default: 'auto',
    },
    userOrgIdAttributeName: { type: String, default: 'ESCOSIRENCourant[0]' },
    userAllOrgsIdAttributeName: { type: String, default: 'ESCOSIREN' },
    orgLogoUrlAttributeName: {
      type: String,
      default: 'otherAttributes.ESCOStructureLogo[0]',
    },
    showFavoritesInSlider: { type: Boolean, default: true },
  },
  data() {
    return {
      backgroundImg: this.forceOrgLogo || this.defaultOrgLogo,
      screenSize: 'medium',
      hideAction: false,
      info: {
        favorites: [],
        organizations: [],
        user: {},
        userOrganization: {},
        portlets: [],
      },
      loadingState: {
        favorites: true,
        portlets: true,
        user: true,
        organization: true,
      },
    };
  },
  computed: {
    _portlets() {
      return this.info.portlets;
    },
    _isHidden() {
      return this.isHidden;
    },
    _screenSize() {
      return this.screenSize;
    },
    _user() {
      return this.info.user;
    },
    _organizations() {
      return this.info.organizations;
    },
    _userOrganization() {
      if (
        Object.keys(this.info.userOrganization).length === 0 &&
        this.info.userOrganization.constructor === Object
      ) {
        this.computeCurrentOrg();
      }
      return this.info.userOrganization;
    },
    _favorites() {
      return this.info.favorites;
    },
    isLoading() {
      return (
        !this.loadingState.favorites ||
        !this.loadingState.portlets ||
        !this.loadingState.user ||
        !this.loadingState.organization
      );
    },
  },
  watch: {
    isHidden: {
      handler() {
        if (!this.isHidden) {
          this.$nextTick(function () {
            this.calculateSize();
          });
        }
      },
    },
  },
  mounted() {
    this.fetchPortlets();
    this.fetchFavorites();
    this.fetchUserInfo();
    this.$nextTick(function () {
      window.addEventListener('resize', this.calculateSize);
      this.calculateSize();
    });
  },
  beforeDestroy() {
    window.removeEventListener('resize', this.calculateSize);
  },
  methods: {
    close(event) {
      const element = document.querySelector('#' + this.id);
      if (element?.parentNode) {
        element.parentNode.style.display = 'none';
        element.setAttribute('is-hidden', true);
      }
      this.callOnClose(event);
    },
    calculateSize() {
      this.screenSize = breakPointName(elementWidth(this.$el));

      switch (this.hideActionMode) {
        case 'auto':
          this.hideAction =
            this.screenSize === 'small' || this.screenSize === 'smaller';
          break;
        case 'never':
          this.hideAction = false;
          break;
        default:
          // case of 'always' hidden
          this.hideAction = true;
      }
    },
    computeCurrentOrg() {
      const currentOrganization = getCurrentOrganization(
        this.info.user,
        this.userOrgIdAttributeName,
        this.info.organizations
      );
      if (currentOrganization !== null) {
        this.info.userOrganization = Object.assign(
          {},
          this.info.userOrganization,
          currentOrganization
        );
        const logo =
          getOrganizationLogo(
            currentOrganization,
            this.orgLogoUrlAttributeName
          ) || this.defaultOrgLogo;
        this.backgroundImg = computeUrl(logo);
      }
    },
    getOrgImgUrl() {
      return this.forceOrgLogo || this.backgroundImg;
    },
    async fetchUserInfo() {
      this.loadingState.user = false;
      this.loadingState.organization = false;
      const { user, organizations } = await fetchUserInfoAndOrg(
        this.userInfoApiUrl,
        this.organizationApiUrl,
        this.userAllOrgsIdAttributeName,
        this.debug
      );
      this.info.user = Object.assign({}, this.info.user, user);
      this.loadingState.user = true;
      this.info.organizations = organizations;
      this.loadingState.organization = true;
    },
    async fetchPortlets() {
      this.loadingState.portlets = false;
      const portlets = await fetchPortlets(
        this.userInfoApiUrl,
        this.portletApiUrl,
        this.debug
      );
      this.info.portlets = portletRegistryToArray(portlets).sort(byPortlet);
      this.loadingState.portlets = true;
    },
    async fetchFavorites() {
      this.loadingState.favorites = false;
      const favoritesTree = await fetchFavorites(
        this.userInfoApiUrl,
        this.layoutApiUrl,
        this.debug
      );
      this.info.favorites = flattenFavorites(favoritesTree);
      this.loadingState.favorites = true;
    },
    actionToggleFav(fname) {
      this.info.favorites = toggleArray(this.info.favorites, fname);
    },
  },
};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style lang="scss" scoped>
.content-menu {
  min-width: 280px;
  background-color: #d0d0d0;

  /* same value as @zindex-navbar-fixed from bootstrap. */
  z-index: 1030;

  * {
    font-family: Roboto, sans-serif;
  }

  > section {
    padding: 0.5em 1.5em;
  }

  header {
    position: relative;
    overflow: hidden;

    > :not(:last-child) {
      position: relative;
      z-index: 1;
    }

    > .wrapper {
      display: flex;
      flex-flow: row nowrap;

      .content-favorites {
        flex-grow: 1;
        filter: none;
        overflow: hidden;
      }
    }

    div.background {
      background-position: center;
      background-repeat: no-repeat;
      background-size: cover;
      position: absolute;
      width: 110%;
      height: 110%;
      overflow: hidden;
      top: 0;
      z-index: 0;
      filter: blur(7px);
    }
  }

  .spinner {
    position: fixed;
    z-index: 1040;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background-color: #545454;
    opacity: 0.7;
    display: flex;
    align-items: center;

    > .vue-simple-spinner {
      opacity: 1;
    }
  }

  &.small,
  &.smaller {
    background-color: #545454;

    > section {
      padding: 0.5em;
    }

    header {
      div.background {
        background-image: none;
      }

      .header-buttons {
        position: absolute;
        width: 100%;
        z-index: 2;
      }

      > .wrapper {
        flex-flow: row wrap;
      }
    }

    > ::v-deep section.content-grid {
      > div {
        background-color: #f3f3f3;

        > .title {
          background-color: #fff;
        }
      }
    }
  }
}
</style>
