// @uportal/esco-content-menu-lit/src/lit-ellipsis.ts
/*Lit*/
import { html, LitElement, css, TemplateResult } from 'lit';
import { customElement, property, query } from 'lit/decorators.js';
/*Mixins*/
import { LitLoggable } from '@mixins/litLoggable';
/*Dependencies*/
import debounce from 'lodash/debounce';

@customElement('lit-ellipsis')
export class Ellipsis extends LitLoggable(LitElement) {
  @property({ type: String })
  message = '';
  @property({ type: Number, attribute: 'line-clamp' })
  clamp = 0;
  @property({ type: String, attribute: 'line-height' })
  height = '22px';
  @property({ type: String, attribute: 'end-char' })
  endChar = '...';
  @property({ type: String, attribute: 'end-html' })
  endHtml = '';

  @query('#sentence')
  sentence!: HTMLDivElement;

  constructor() {
    super();
    this.debugLog('Component loaded');
  }

  connectedCallback(): void {
    super.connectedCallback();
    window.addEventListener('resize', this.debounceRun.bind(this), false);
  }

  disconnectedCallback(): void {
    super.connectedCallback();
    window.removeEventListener('resize', this.debounceRun.bind(this), false);
  }

  firstUpdated(): void {
    this.debounceRun();
  }

  debounceRun = debounce(this.run, 500);

  run(): void {
    if (this.message?.length <= 0) return;
    const lineHeight = parseInt(this.height, 10);

    this.sentence.innerHTML = '';
    this.sentence.style.height = '100%';
    const availableHeight =
      this.sentence.getBoundingClientRect().height || lineHeight;
    if (availableHeight < lineHeight) return;

    this.sentence.innerHTML = this.message;
    this.sentence.style.height = 'auto';
    let height = this.sentence.getBoundingClientRect().height || lineHeight;
    const start = 0;
    let end = this.message.length;

    const maxHeight = lineHeight * Math.trunc(availableHeight / lineHeight);
    const goalMaxHeight = lineHeight * (this.clamp > 0 ? this.clamp : 1);
    const finalMaxHeight =
      this.clamp > 0 && goalMaxHeight < availableHeight
        ? goalMaxHeight
        : maxHeight;

    if (height < finalMaxHeight) return;

    while (Math.abs(end - start) > 1) {
      const half = Math.ceil((end - start) / 2);
      this.sentence.innerHTML = this.message.substring(0, half).trim();
      height = this.sentence.getBoundingClientRect().height || lineHeight;
      if (height <= finalMaxHeight) {
        break;
      } else {
        end = half;
      }
    }
    while (height > finalMaxHeight) {
      this.sentence.innerHTML = this.sentence.innerHTML
        .substring(0, this.sentence.innerHTML.trimEnd().length - 1)
        .trim();
      height = this.sentence.getBoundingClientRect().height || lineHeight;
    }

    const endStr =
      this.endHtml !== '' ? this.endHtml.replace(/<[^>]+>/g, '') : '';
    const endLen =
      this.endChar === '...' ? 3 : endStr.length + this.endChar.length;

    const nodeLen = this.sentence.innerHTML.trimRight().length;
    const nodeDelStr = this.sentence.innerHTML
      .substring(nodeLen - endLen, nodeLen)
      .trim();
    const match = nodeDelStr.match(/\s+/g);
    const extraLen = match && match.length ? match.length : 0;
    this.sentence.innerHTML =
      this.sentence.innerHTML.substring(0, nodeLen - endLen - extraLen).trim() +
      this.endChar +
      this.endHtml;
  }

  render(): TemplateResult {
    return html` <div class="autofit-ellipsis" id="sentence">...</div> `;
  }

  static styles = css`
    .autofit-ellipsis {
      height: 100%;
    }
  `;
}

// @uportal/esco-content-menu/src/components/Ellipsis.vue
<template>
  <div ref="sentence" />
</template>

<script>
// Code translation from https://github.com/jypblue/vue-ellipsis
// intregration due to a problem : https://github.com/jypblue/vue-ellipsis/issues/2

export default {
  name: 'Ellipsis',
  props: {
    message: {type: String, default: ''},
    lineClamp: {type: Number, default: 1},
    lineHeight: {type: String, default: '22px'},
    endChar: {type: String, default: '...'},
    endHtml: {type: String, default: ''},
  },
  mounted() {
    this.$nextTick(function() {
      setTimeout(() => {
        this.handleSubstrSentence();
      }, 200);
    });
  },
  methods: {
    handleSubstrSentence() {
      const stNode = this.$refs.sentence;
      const html = this.message;
      if (html.length === 0) {
        // throw new Error('the String is empty');
        return false;
      }
      stNode.innerHTML = html;

      let startPos = 0;
      let endPos = html.length;

      const stNodeLineHeight = parseInt(this.lineHeight, 10);
      const maxHeight = stNodeLineHeight * this.lineClamp;

      let stNodeHeight =
        stNode.getBoundingClientRect().height || stNodeLineHeight;

      if (stNodeHeight > maxHeight) {
        while (Math.abs(endPos - startPos) > 1) {
          const half = Math.ceil((endPos + startPos) / 2);
          const newHtml = html.substring(0, half).trim();
          stNode.innerHTML = newHtml;
          stNodeHeight =
            stNode.getBoundingClientRect().height || stNodeLineHeight;

          if (stNodeHeight <= maxHeight) {
            startPos = half;
          } else {
            endPos = half;
          }
        }

        while (stNodeHeight > maxHeight) {
          const newHtml = stNode.innerHTML.substring(
              0,
              stNode.innerHTML.trimRight().length - 1
          );
          stNode.innerHTML = newHtml.trim();
          stNodeHeight =
            stNode.getBoundingClientRect().height || stNodeLineHeight;
        }

        const endStr =
          this.endHtml !== '' ? this.endHtml.replace(/<[^>]+>/g, '') : '';
        const endLen =
          this.endChar === '...' ? 3 : endStr.length + this.endChar.length;

        const stNodeLen = stNode.innerHTML.trimRight().length;
        const stNodeDelStr = stNode.innerHTML
            .substring(stNodeLen - endLen, stNodeLen)
            .trim();
        const match = stNodeDelStr.match(/\s+/g);
        const extraLen = match && match.length ? match.length : 0;
        const newHtml =
          stNode.innerHTML.substring(0, stNodeLen - endLen - extraLen).trim() +
          this.endChar +
          this.endHtml;
        stNode.innerHTML = newHtml;
      }
    },
  },
};
</script>

<style scoped>
</style>
