// @uportal/esco-content-menu/src/components/ContentGrid.vue
<template>
  <section
    :class="['parent-' + parentScreenSize, elementSize]"
    :style="'background-color:' + backgroundColor"
    class="content-grid">
    <div>
      <div
        class="title"
        v-if="!hideTitle">
        <slot name="header-left">
          <h1>
            {{ translate("message.services.title") }}
          </h1>
        </slot>
        <slot name="header-right">
          <div
            :class="visible ? 'opened' : 'closed'"
            class="filter custom-caret">
            <input
              :title="translate('message.services.filter')"
              v-model.trim="filterValue"
              :placeholder="translate('message.services.filter')"
              type="text"
              @focus="filterValue = ''"
              autofocus>
            <select v-model="filterCategory">
              <option
                class="default"
                selected
                value="">
                {{ translate('message.filter.selectOption') }}
              </option>
              <option
                v-for="category in allCategories"
                :value="category"
                :label="category"
                :key="category">
                {{ category }}
              </option>
            </select>
            <div @click="visible = !visible">
              <i
                class="fa fa-search"
                aria-hidden="true" />
            </div>
          </div>
        </slot>
      </div>
      <div class="flex-grid">
        <div
          v-for="portlet in filteredPortlets"
          :key="portlet.id"
          class="flex-item ma-3 text-xs-center">
          <a
            :href="portlet.renderUrl"
            :target="portlet.layoutObject.altMaxUrl ? '_blank' : '_self'"
            :rel="portlet.layoutObject.altMaxUrl ? 'noopener noreferrer' : ''"
            class="no-style">
            <portlet-card
              :portlet-desc="portlet"
              :is-favorite="isFavorite(portlet.fname)"
              :size="_portletCardSize"
              :hide-action="hideAction"
              :call-after-action="actionToggleFav"
              :favorite-api-url="favoriteApiUrl"
              :user-info-api-url="userInfoApiUrl" />
          </a>
        </div>
      </div>
      <slot name="footer">
        <select
          class="footer-categories"
          v-if="showFooterCategories"
          v-model="filterCategory">
          <option
            class="default"
            selected
            value="">
            {{ translate('message.filter.selectOption') }}
          </option>
          <option
            v-for="category in allCategories"
            :value="category"
            :label="category"
            :key="category">
            {{ category }}
          </option>
        </select>
      </slot>
    </div>
  </section>
</template>

<script>
import i18n from '../i18n.js';
import PortletCard from './PortletCard';
import fetchPortlets from '../services/fetchPortlets';
import byPortlet from '../services/sortByPortlet';
import fetchFavorites from '../services/fetchFavorites';
import flattenFavorites from '../services/flattenFavorites';
import toggleArray from '../services/toggleArray';
import {
  elementWidth,
  breakPointName,
  sizeValidator,
} from '../services/sizeTools';

export default {
  name: 'ContentGrid',
  components: {
    PortletCard,
  },
  props: {
    hideTitle: {type: Boolean, default: false},
    backgroundColor: {type: String, default: 'rgba(0, 0, 0, 0)'},
    callAfterAction: {type: Function, default: undefined},
    favoriteApiUrl: {
      type: String,
      default:
        process.env.VUE_APP_PORTAL_CONTEXT +
        process.env.VUE_APP_FAVORITES_PORTLETS_URI,
    },
    contextApiUrl: {
      type: String,
      default: process.env.VUE_APP_PORTAL_CONTEXT,
    },
    userInfoApiUrl: {
      type: String,
      default:
        process.env.VUE_APP_PORTAL_CONTEXT + process.env.VUE_APP_USER_INFO_URI,
    },
    /**
     * Warning the default value as undefined permit to distinct if the component should manage favorites locally.
     */
    favorites: {type: Array, default: undefined},
    parentScreenSize: {
      validator: sizeValidator,
      default: 'medium',
    },
    portletCardSize: {
      validator: (value) => sizeValidator(value, true),
      default: 'auto',
    },
    hideAction: {type: Boolean, default: false},
    /**
     * Warning the default value as undefined permit to distinct if the component should manage portlets locally.
     */
    portlets: {type: Array, default: undefined},
    showFooterCategories: {type: Boolean, default: false},
  },
  data() {
    return {
      filterValue: '',
      filterCategory: '',
      visible: false,
      elementSize: this.parentScreenSize,
      localPortlets: [],
      localFavorites: [],
    };
  },
  computed: {
    _portletCardSize() {
      this.calculateSize();
      if (this.portletCardSize === 'auto') {
        return this.elementSize;
      }
      return this.portletCardSize;
    },
    allCategories() {
      const portlets = this.portlets || this.localPortlets;
      const allCategories = portlets.flatMap(({categories}) => categories);
      const uniqueCategories = [...new Set(allCategories)];
      return uniqueCategories.sort();
    },
    filteredPortlets() {
      const portlets = this.portlets || this.localPortlets;
      const filterValue = this.filterValue.toLowerCase();
      const filterCategory = this.filterCategory.toLowerCase();

      if (filterValue === '' && filterCategory === '') {
        return portlets;
      }

      return portlets.filter(
          ({categories, title, name, description}) =>
            (filterCategory === '' ||
            categories.some((cat) =>
              cat.toLowerCase().includes(filterCategory)
            )) &&
          (filterValue === '' ||
            (categories.some((cat) =>
              cat.toLowerCase().includes(filterValue)
            ) ||
              title.toLowerCase().includes(filterValue) ||
              name.toLowerCase().includes(filterValue) ||
              description.toLowerCase().includes(filterValue)))
      );
    },
  },
  beforeMount() {
    window.addEventListener('gridNeedCategories', this.emitAllCategories);
    window.addEventListener('gridCategoryFilter', this.setFilterCategory);
  },
  mounted() {
    if (!this.portlets) {
      this.fetchPortlets();
    }
    if (!this.favorites) {
      this.fetchFavorites();
    }
    this.$nextTick(function() {
      window.addEventListener('resize', this.calculateSize);
      this.calculateSize();
    });
  },
  beforeDestroy() {
    window.removeEventListener('gridCategoryFilter', this.setFilterCategory);
    window.removeEventListener('gridNeedCategories', this.emitAllCategories);
    window.removeEventListener('resize', this.calculateSize);
  },
  methods: {
    translate(text, lang) {
      return i18n.t(text, lang);
    },
    isFavorite(fname) {
      const favorites = this.favorites || this.localFavorites;
      return favorites.includes(fname);
    },
    async fetchPortlets() {
      const portlets = await fetchPortlets(this.contextApiUrl);
      this.localPortlets = portlets.sort(byPortlet);
    },
    async fetchFavorites() {
      const favoritesTree = await fetchFavorites(this.contextApiUrl);
      this.localFavorites = flattenFavorites(favoritesTree);
    },
    calculateSize() {
      this.elementSize = breakPointName(elementWidth(this.$el));
    },
    actionToggleFav(fname) {
      /**
       * use case:
       * if used independently or without external component need on favorites we should manage locally favorited
       * the callAfterAction function is needed to manage favorites from parent element.
       */
      if (this.callAfterAction) {
        return this.callAfterAction(fname);
      }
      if (!this.favorites) {
        this.localFavorites = toggleArray(this.localFavorites, fname);
      }
    },
    setFilterCategory(e) {
      this.filterCategory = e.detail || '';
    },
    emitAllCategories(e) {
      this.$nextTick(() => {
        // nextTick() waits for data to be resolved
        if (this.allCategories.length > 0) {
          const event = new CustomEvent('gridCategories', {
            detail: this.allCategories,
          });
          window.dispatchEvent(event);
        }
      });
    },
  },
};
</script>

<style lang="scss" scoped>
$searchSize: 32px;

.content-grid {
  min-width: 250px;

  ::placeholder {
    font-style: italic;
  }

  ::-webkit-input-placeholder {
    font-style: italic;
  }

  ::-ms-input-placeholder {
    font-style: italic;
  }

  ::-moz-placeholder {
    font-style: italic;
  }

  :-moz-placeholder {
    font-style: italic;
  }

  :-ms-input-placeholder {
    font-style: italic;
  }

  .fa {
    display: inline-block;
    font: normal normal normal 14px/1 FontAwesome, sans-serif;
    font-size: inherit;
    text-rendering: auto;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
  }

  .fa-search::before {
    content: '\f002';
  }

  .footer-categories {
    display: inline-block;
    width: 100%;
    max-width: 50rem;
    height: calc(2.25rem + 2px);
    padding: 0.375rem 1.75rem 0.375rem 0.75rem;
    line-height: 1.5;
    color: #495057;
    vertical-align: middle;
    background-color: #fff;
    background-size: auto auto;
    background-size: 8px 10px;
    border: 1px solid #ced4da;
    border-radius: 0.25rem;
    -webkit-appearance: none;
    -moz-appearance: none;
    appearance: none;
  }

  > div {
    display: block;
    color: #000;

    > .title {
      padding: 0 20px;
      margin-bottom: 15px;
      text-transform: uppercase;
      display: flex;
      flex-flow: row wrap;
      justify-content: space-between;

      > h1 {
        margin-bottom: 15px;
        margin-top: 15px;
        font-weight: normal;
        font-size: 24px;
      }

      > .filter {
        margin: auto 0;
        width: 100%;
        height: 32px;
        max-width: 400px;
        display: flex;
        flex-flow: row nowrap;

        /* custom caret to override bad firefox one */
        &.custom-caret {
          position: relative;
          cursor: pointer;

          &::after {
            content: '';
            position: absolute;
            width: 0;
            height: 0;
            display: inline-block;
            top: 48%;
            right: 10px;
            border-top: 6px solid #000;
            border-left: 6px solid transparent;
            border-right: 6px solid transparent;
            pointer-events: none;
          }

          select {
            -webkit-appearance: none;
            -moz-appearance: none;
            padding: 5px 24px 5px 5px;

            &::-ms-expand {
              display: none;
            }
          }
        }

        input,
        select {
          border: none;
          height: 100%;

          /* prettier-ignore */
          box-shadow:
            0 2px 2px 0 rgba(0, 0, 0, 0.14),
            0 3px 1px -2px rgba(0, 0, 0, 0.12),
            0 1px 5px 0 rgba(0, 0, 0, 0.2);
          outline: none;
          padding: 0;
          margin: 0;
        }

        input {
          line-height: 32px;
          border-top-left-radius: 48px;
          border-bottom-left-radius: 48px;
          width: 60%;
          text-indent: 10px;
          font-size: 16px;
        }

        select {
          border-top-right-radius: 48px;
          border-bottom-right-radius: 48px;
          width: 40%;

          option.default {
            font-style: italic;
            color: grey;
          }
        }

        > div {
          display: none;
        }
      }
    }

    .flex-grid {
      display: flex;
      flex-flow: row wrap;
      justify-content: center;

      .flex-item {
        margin: 20px auto;
        padding: 0 2.5px;
      }

      /** fix IE flexbox bug on margin auto https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/14593426/. */
      @media screen and (-ms-high-contrast: active), (-ms-high-contrast: none) {
        .flex-item {
          margin: 20px 5px;
        }
      }
    }

    a.no-style {
      text-decoration: none;
      color: inherit;
    }
  }

  &.small,
  &.smaller {
    > div {
      border-radius: 5px;

      > .title {
        position: relative;
        border-radius: 5px;

        > h1 {
          margin-right: $searchSize;
        }

        > .filter {
          margin: auto 0;
          position: absolute;
          display: flex;
          flex-flow: row nowrap;
          width: calc(100% - 30px);
          height: calc(100% - 10px);
          padding: 5px 0;
          max-width: unset;
          right: 15px;

          &.closed {
            width: $searchSize;

            > input,
            > select,
            &::after {
              visibility: hidden;
              padding: 0;
              display: none;
            }
          }

          > div {
            display: -webkit-box;
            display: -ms-flexbox;
            display: flex;
            align-items: center;
            text-align: center;

            > .fa {
              margin-left: 5px;
              font-size: $searchSize;
              opacity: 0.4;
            }
          }

          &.opened {
            transition: width 1s;
            backface-visibility: hidden;

            &::after {
              right: 40px;
            }

            @media screen and (max-width: 400px) {
              flex-flow: column wrap;
              height: 100%;

              > input,
              > select {
                width: calc(100% - 42px);
                height: 50%;
                border-radius: unset;
              }

              &::after {
                right: 50px;
                top: 75%;
              }

              > div {
                flex: 1 1 100%;
              }
            }

            > div > .fa {
              opacity: 1;
            }
          }
        }
      }
    }
  }
}
</style>

// @uportal/esco-content-menu-lit/src/content-grid.ts
/*Lit*/
import {
  html,
  LitElement,
  css,
  unsafeCSS,
  TemplateResult,
  PropertyValues,
} from 'lit';
import { customElement, property, state } from 'lit/decorators.js';
import { unsafeHTML } from 'lit-html/directives/unsafe-html.js';
import { classMap } from 'lit/directives/class-map.js';
import { styleMap } from 'lit/directives/style-map.js';
/*SCSS*/
import ContentGridScss from '@styles/content-grid.scss';
/*Localization*/
import { msg, localized, str } from '@lit/localize';
import { setLocale } from '@helpers/localization';
import langHelper from '@helpers/langHelper';
/*Mixins*/
import { LitLoggable } from '@mixins/litLoggable';
/*Services*/
import portletService from '@services/portletService';
import favoritesService from '@services/favoritesService';
/*Helpers*/
import sizeHelper from '@helpers/sizeHelper';
/*Dependencies*/
import { icon } from '@fortawesome/fontawesome-svg-core';
import { faSearch } from '@fortawesome/free-solid-svg-icons/faSearch';
import { matchSorter } from 'match-sorter';
import debounce from 'lodash/debounce';
/*Components*/
import './portlet-card';

@localized()
@customElement('esco-content-grid')
export class ContentGrid extends LitLoggable(LitElement) {
  @property({ type: Array })
  messages = [];
  @property({
    type: String,
    hasChanged(newVal: string) {
      return sizeHelper.validate(newVal, true, true);
    },
    attribute: 'parent-screen-size',
  })
  parentScreenSize = 'medium';
  @property({
    type: String,
    hasChanged(newVal: string) {
      return sizeHelper.validate(newVal, true, true);
    },
    attribute: 'portlet-card-size',
  })
  cardSize = 'auto';
  @property({
    type: String,
    hasChanged(newVal: string) {
      return sizeHelper.validate(newVal, true, true);
    },
    attribute: false,
  })
  elementSize = 'medium';
  @property({ type: String, attribute: 'background-color' })
  backgroundColor = 'rgba(0, 0, 0, 0)';
  @property({ type: String, attribute: 'context-api-url' })
  contextApiUrl = process.env.APP_PORTAL_CONTEXT ?? '';
  @property({ type: String, attribute: 'favorite-api-url' })
  favoriteApiUrl =
    (process.env.APP_PORTAL_CONTEXT ?? '') +
    (process.env.APP_FAVORITES_PORTLETS_URI ?? '');
  @property({ type: String, attribute: 'layout-api-url' })
  layoutApiUrl =
    (process.env.APP_PORTAL_CONTEXT ?? '') +
    (process.env.APP_FAVORITES_URI ?? '');
  @property({ type: String, attribute: 'portlet-api-url' })
  portletApiUrl =
    (process.env.APP_PORTAL_CONTEXT ?? '') +
    (process.env.APP_BROWSABLE_PORTLETS_URI ?? '');
  @property({ type: String, attribute: 'user-info-api-url' })
  userInfoApiUrl =
    (process.env.APP_PORTAL_CONTEXT ?? '') +
    (process.env.APP_USER_INFO_URI ?? '');
  @property({ type: String, attribute: 'card-hover-src' })
  cardHoverSrc = 'none';
  @property({ type: Array, reflect: true })
  favorites = [];
  @property({ type: Array, attribute: 'all-categories', reflect: true })
  allCategories: string[] = [];
  @property({ type: Array })
  portlets = [];
  @property({ type: Boolean, attribute: 'hide-title' })
  hideTitle = false;
  @property({ type: Boolean, attribute: 'show-footer-categories' })
  showFooterCategories = false;
  @property({ type: Boolean, attribute: 'hide-action' })
  hideAction = false;
  @property({ type: Boolean, attribute: 'use-external-filter' })
  useExternalFilter = false;
  @property({ type: Boolean })
  debug = false;
  @property({ type: Boolean, attribute: 'portlet-background-is-dark' })
  portletBackgroundIsDark = false;

  @state()
  isVisible = false;
  @state()
  filterValue = '';
  @state()
  filterCategory = '';
  @state()
  localFavorites: string[] | undefined = undefined;
  @state()
  localPortlets: Portlet[] | undefined = undefined;

  constructor() {
    super();
    this.debugLog('Component loaded');

    const lhOpts = {
      languageCodeOnly: true,
      availableLanguages: ['fr', 'en'],
      defaultLanguage: 'en',
    };
    const lang = langHelper.getPageLang(lhOpts);
    setLocale(lang);
    langHelper.setLocale(lang);
  }

  connectedCallback(): void {
    super.connectedCallback();

    window.addEventListener(
      'esco-cm-grid-filter',
      this.getExternalFilter.bind(this) as EventListener
    );

    window.addEventListener(
      'esco-cm-request-grid-filter',
      this.sendExternalFilter as EventListener
    );

    window.addEventListener(
      'esco-cm-request-categories',
      this.sendCategories as EventListener
    );

    window.addEventListener(
      'gridFavoritesUpdated',
      this.reload.bind(this) as EventListener
    );
    this.loadData();
  }

  disconnectedCallback(): void {
    super.connectedCallback();

    window.removeEventListener(
      'esco-cm-grid-filter',
      this.getExternalFilter as EventListener
    );

    window.removeEventListener(
      'esco-cm-request-grid-filter',
      this.sendExternalFilter as EventListener
    );

    window.removeEventListener(
      'esco-cm-request-categories',
      this.sendCategories as EventListener
    );

    window.removeEventListener(
      'gridFavoritesUpdated',
      this.reload.bind(this) as EventListener
    );
    window.removeEventListener(
      'resize',
      this.debounceCalculateSize.bind(this),
      false
    );
  }

  willUpdate(changedProperties: PropertyValues): void {
    if (changedProperties.has('parentScreenSize')) {
      this.elementSize = this.parentScreenSize;
    }
    if (changedProperties.has('messages')) {
      langHelper.setReference(this.messages);
    }
  }

  loadData(): void {
    if (this.portlets.length < 1) this.fetchPortlets();
    if (this.favorites.length < 1) this.fetchFavorites();
    window.addEventListener(
      'resize',
      this.debounceCalculateSize.bind(this),
      false
    );
  }

  getExternalFilter(e: CustomEvent): void {
    if (
      e.detail?.category &&
      this.allCategories.includes(e.detail.category) &&
      this.filterCategory != e.detail.category
    ) {
      this.filterCategory = e.detail.category;
    }

    if (e.detail?.value && this.filterValue != e.detail.value) {
      this.filterValue = e.detail.value;
    }
  }

  sendExternalFilter(): void {
    const filterEvt = new CustomEvent('esco-cm-grid-filter', {
      detail: {
        category: this.filterCategory,
        value: this.filterValue,
      },
    });
    window.dispatchEvent(filterEvt);
  }

  sendCategories(): void {
    const catsEvt = new CustomEvent('esco-cm-categories', {
      detail: {
        categories: this.allCategories,
      },
    });
    window.dispatchEvent(catsEvt);
  }

  reload(): void {
    if (!this.debug) this.fetchPortlets();
  }

  debounceCalculateSize = debounce(this.calculateSize, 500);

  calculateSize(): void {
    const element = this.shadowRoot?.getElementById('content-grid');
    const size = sizeHelper.elementWidth(element);
    this.elementSize = sizeHelper.breakPointName(size);
  }

  calculateCategories(): void {
    const portlets =
      this.portlets.length > 0 ? this.portlets : this.localPortlets;
    const allCategories = portlets?.flatMap(({ categories }) => categories);
    this.allCategories = [...new Set(allCategories)].sort() as string[];
    this.sendCategories();
  }

  async fetchPortlets(): Promise<void> {
    const portlets = await portletService.fetch(
      this.userInfoApiUrl,
      this.portletApiUrl,
      this.debug
    );
    if (portlets !== undefined) {
      this.localPortlets = portletService.portletRegistryToArray(portlets);
    }
  }

  async fetchFavorites(): Promise<void> {
    const favoritesTree = await favoritesService.fetch(
      this.userInfoApiUrl,
      this.layoutApiUrl,
      this.debug
    );

    this.localFavorites = favoritesService.flattenFavorites(favoritesTree);
  }

  filteredPortlets(): Portlet[] {
    const portlets: Portlet[] =
      this.portlets.length > 0 ? this.portlets : this.localPortlets ?? [];
    const categoryFilter =
      this.filterCategory.trim() === ''
        ? // no filter applied return everything
          (portlets: Portlet[]): Portlet[] => portlets
        : // filter by category
          (portlets: Portlet[]): Portlet[] =>
            matchSorter(portlets, this.filterCategory, {
              keys: ['categories'],
              threshold: matchSorter.rankings.EQUAL,
            });
    const valueFilter =
      this.filterValue.trim() === ''
        ? // no filter applied return everything
          (portlets: Portlet[]): Portlet[] => portlets
        : // filter and sort by best match
          (portlets: Portlet[]): Portlet[] =>
            matchSorter(portlets, this.filterValue, {
              keys: ['title', 'name', 'description'],
              threshold: matchSorter.rankings.ACRONYM,
            });

    return valueFilter(
      categoryFilter(portlets).sort(portletService.sortPortlets)
    );
  }

  portletCardSize(): string {
    // this.calculateSize();
    if (this.cardSize === 'auto') {
      return this.elementSize;
    }
    return this.cardSize;
  }

  getRenderPortletUrl(portlet: Portlet): string {
    return portletService.getRenderUrl(portlet, this.contextApiUrl);
  }
  hasAlternativeMaximizedUrl(portlet: Portlet): string {
    return portletService.getAlternativeMaximizedUrl(portlet);
  }
  isFavorite(fname: string): boolean {
    const favorites =
      this.favorites.length > 0 ? this.favorites : this.localFavorites;
    return favorites?.includes(fname as never) || false;
  }
  toggleFavorite(e: CustomEvent): void {
    const GFUevent = new CustomEvent('gridFavoritesUpdated', {
      bubbles: true,
      detail: e.detail,
    });
    window.dispatchEvent(GFUevent);
    const TFevent = new CustomEvent('toggle-favorite', {
      bubbles: true,
      detail: e.detail,
    });
    this.dispatchEvent(TFevent);

    if (this.favorites.length == 0) {
      if (this.localFavorites === undefined) this.localFavorites = [];
      if (!this.localFavorites.includes(e.detail.fname)) {
        this.localFavorites.push(e.detail.fname);
      } else {
        this.localFavorites.splice(
          this.localFavorites.indexOf(e.detail.fname),
          1
        );
      }
    }

    if (
      !this.debug &&
      e.detail?.chanId !== undefined &&
      this.portlets.length >= 1
    ) {
      if (e.detail?.isFavorite) {
        favoritesService.add(
          this.userInfoApiUrl,
          this.favoriteApiUrl,
          e.detail.chanId
        );
      } else {
        favoritesService.remove(
          this.userInfoApiUrl,
          this.favoriteApiUrl,
          e.detail.chanId
        );
      }
    }
  }

  render(): TemplateResult {
    this.calculateCategories();
    return html`
      <section
        class="content-grid ${classMap({
          ['parent-' + this.parentScreenSize]: true,
          [this.elementSize]: true,
        })}"
        style="${styleMap({ 'background-color': this.backgroundColor })}"
        id="content-grid"
      >
        <div>
          ${this.hideTitle
            ? html``
            : html`
                <div class="title">
                  <slot name="header-left">
                    <h1>
                      ${langHelper.localTransation(
                        'services.title',
                        msg(str`All the services`)
                      )}
                    </h1>
                  </slot>
                  <slot name="header-right">${this.renderCatFilter()}</slot>
                </div>
              `}

          <div class="preamble">
            <slot name="preamble" class="preamble"></slot>
          </div>
          <div class="flex-grid">${this.renderPortlets()}</div>
          <slot name="footer">${this.renderCatFilterFooter()} </slot>
        </div>
      </section>
    `;
  }

  renderCatFilter(): TemplateResult {
    if (this.hideTitle) {
      return html``;
    } else {
      return html`
        <div
          class="filter custom-caret ${classMap({
            opened: this.isVisible,
            closed: !this.isVisible,
          })}"
        >
          <input
            title="${langHelper.localTransation(
              'services.filter',
              msg(str`Search a service...`)
            )}"
            .value="${this.filterValue}"
            placeholder="${langHelper.localTransation(
              'services.filter',
              msg(str`Search a service...`)
            )}"
            type="text"
            @keyup=${this.valFilterChange}
            @focus=${() => {
              this.filterValue = '';
              this.sendExternalFilter();
            }}
            autofocus
          />
          <select id="catFilter" @change=${this.catFilterChange}>
            <option class="default" selected value="">
              ${langHelper.localTransation(
                'filter.selectOption',
                msg(str`All the categories`)
              )}
            </option>
            ${this.allCategories.map(
              (cat) =>
                html`<option
                  value="${(cat as string) ?? ''}"
                  ?selected=${this.filterCategory === cat}
                >
                  ${cat}
                </option> `
            )}
          </select>
          <div
            @click="${() => {
              this.isVisible = !this.isVisible;
            }}"
          >
            ${unsafeHTML(`${icon(faSearch).html}`)}
          </div>
        </div>
      `;
    }
  }

  renderCatFilterFooter(): TemplateResult {
    if (this.showFooterCategories) {
      return html`
        <select class="footer-categories" @change=${this.catFilterChange}>
          <option class="default" selected value="">
            ${langHelper.localTransation(
              'filter.selectOption',
              msg(str`All the categories`)
            )}
          </option>
          ${this.allCategories.map(
            (cat) =>
              html`<option
                value="${(cat as string) ?? ''}"
                ?selected=${this.filterCategory === cat}
              >
                ${cat}
              </option> `
          )}
        </select>
      `;
    } else {
      return html``;
    }
  }

  renderPortlets(): TemplateResult {
    const portlets = this.filteredPortlets();

    const cardSize = this.portletCardSize();

    const template = html`${portlets.map((portlet) => {
      return html`
        <div
          data-key="${portlet.id}"
          class="flex-item ma-3 text-xs-center ${classMap({
            ['portlet-card-' + cardSize]: true,
          })}"
        >
          <a
            href="${this.getRenderPortletUrl(portlet)}"
            target="${this.hasAlternativeMaximizedUrl(portlet)
              ? '_blank'
              : '_self'}"
            rel="${this.hasAlternativeMaximizedUrl(portlet)
              ? 'noopener noreferrer'
              : ''}"
            class="no-style"
          >
            <esco-portlet-card
              .messages=${this.messages}
              .portletDesc="${portlet}"
              ?is-favorite=${this.isFavorite(portlet.fname)}
              size="${this.portletCardSize()}"
              card-hover-src="${this.cardHoverSrc}"
              ?hide-action=${this.hideAction}
              ?background-is-dark="${this.portletBackgroundIsDark}"
              ?debug="${this.debug}"
              @toggle-favorite=${this.toggleFavorite}
            ></esco-portlet-card>
          </a>
        </div>
      `;
    })} `;

    return template;
  }

  catFilterChange(e: Event): void {
    const target = (e.target || e.srcElement) as HTMLInputElement;
    const value = target?.value;
    this.debounceCatFilterChange(value);
  }
  debounceCatFilterChange = debounce((value) => {
    this.filterCategory = value;
    this.sendExternalFilter();
  }, 500);

  valFilterChange(e: Event): void {
    const target = (e.target || e.srcElement) as HTMLInputElement;
    const value = target?.value;
    this.debounceValFilterChange(value);
  }
  debounceValFilterChange = debounce((value) => {
    this.filterValue = value;
    this.sendExternalFilter();
  }, 500);

  static styles = css`
    ${unsafeCSS(ContentGridScss)}
  `;
}
