// @uportal/esco-content-menu/src/components/HamburgerMenu.vue
<template>
  <div class="hamburger-menu">
    <div
      class="content-menu-toggle"
      aria-label="Menu"
      role="button"
      title="Menu"
      aria-expanded="false"
      aria-haspopup="true"
      aria-controls="content-menu"
      @click="toggleMenu($event)"
    >
      <slot name="menu-icon">
        <div class="menu-wrapper">
          <div class="hm-line" />
          <div class="hm-line" />
          <div class="hm-line" />
        </div>
      </slot>
    </div>

    <slot name="menu-content">
      <content-menu
        v-if="append"
        :messages="messages"
        :switch-org-portlet-url="switchOrgPortletUrl"
        :call-on-close="toggleMenu"
        :context-api-url="contextApiUrl"
        :favorite-api-url="favoriteApiUrl"
        :layout-api-url="layoutApiUrl"
        :organization-api-url="organizationApiUrl"
        :portlet-api-url="portletApiUrl"
        :user-info-api-url="userInfoApiUrl"
        :debug="debug"
        :default-org-logo="defaultOrgLogo"
        :favorites-portlet-card-size="favoritesPortletCardSize"
        :grid-portlet-card-size="gridPortletCardSize"
        :hide-action-mode="hideActionMode"
        :is-hidden="!visible"
        :user-info-portlet-url="userInfoPortletUrl"
        :sign-out-url="signOutUrl"
        :user-org-id-attribute-name="userOrgIdAttributeName"
        :user-all-orgs-id-attribute-name="userAllOrgsIdAttributeName"
        :org-logo-url-attribute-name="orgLogoUrlAttributeName"
        :show-favorites-in-slider="showFavoritesInSlider"
        default-class="toggler-menu"
        visible-class="active-menu"
      />
    </slot>
  </div>
</template>

<script>
import ContentMenu from './ContentMenu';
import { sizeValidator } from '../services/sizeTools';
import i18nMixin from '../mixins/i18n.js';

export default {
  name: 'HamburgerMenu',
  mixins: [i18nMixin],
  components: {
    ContentMenu
  },
  props: {
    contextApiUrl: {
      type: String,
      default: process.env.VUE_APP_PORTAL_CONTEXT
    },
    favoriteApiUrl: {
      type: String,
      default:
        process.env.VUE_APP_PORTAL_CONTEXT +
        process.env.VUE_APP_FAVORITES_PORTLETS_URI
    },
    layoutApiUrl: {
      type: String,
      default:
        process.env.VUE_APP_PORTAL_CONTEXT + process.env.VUE_APP_FAVORITES_URI
    },
    organizationApiUrl: {
      type: String,
      default: null
    },
    portletApiUrl: {
      type: String,
      default:
        process.env.VUE_APP_PORTAL_CONTEXT +
        process.env.VUE_APP_BROWSABLE_PORTLETS_URI
    },
    userInfoApiUrl: {
      type: String,
      default:
        process.env.VUE_APP_PORTAL_CONTEXT + process.env.VUE_APP_USER_INFO_URI
    },
    debug: { type: Boolean, default: false },
    signOutUrl: { type: String, default: process.env.VUE_APP_LOGOUT_URL },
    defaultOrgLogo: { type: String, required: true },
    userInfoPortletUrl: { type: String, default: '' },
    switchOrgPortletUrl: { type: String, default: '' },
    favoritesPortletCardSize: {
      validator: value => sizeValidator(value, true),
      default: 'auto'
    },
    gridPortletCardSize: {
      validator: value => sizeValidator(value, true),
      default: 'auto'
    },
    hideActionMode: {
      validator: value => ['auto', 'always', 'never'].includes(value),
      default: 'auto'
    },
    userOrgIdAttributeName: { type: String, default: 'ESCOSIRENCourant[0]' },
    userAllOrgsIdAttributeName: { type: String, default: 'ESCOSIREN' },
    orgLogoUrlAttributeName: {
      type: String,
      default: 'otherAttributes.ESCOStructureLogo[0]'
    },
    showFavoritesInSlider: { type: Boolean, default: true }
  },
  data() {
    return {
      visible: false,
      append: false
    };
  },
  mounted() {
    this.$nextTick(function() {
      this.append = true;
    });
  },
  methods: {
    toggleMenu(event) {
      event.preventDefault();
      this.visible = !this.visible;
      const html = document.querySelector('html');
      if (html) {
        html.style.overflowY = this.visible ? 'hidden' : 'auto';
      }
    }
  }
};
</script>

<style lang="scss" scoped>
.hamburger-menu {
  > .content-menu-toggle {
    color: #fff;
    text-decoration: none;
    cursor: pointer;
    padding: 5px 0;

    &:hover > .menu-wrapper > .hm-line {
      opacity: 0.7;
    }

    > .menu-wrapper {
      margin: 0 10px;

      > .hm-line {
        height: 2px;
        background-color: #fff;
        margin: 5px 0;
        width: 25px;
      }
    }
  }

  .toggler-menu {
    position: fixed;
    width: 100%;
    height: 100%;
    top: 0;
    left: 0;
    overflow-y: scroll;
    visibility: hidden;
    opacity: 0;
    transition: opacity 600ms, visibility 600ms;
    animation: fade 600ms;
  }

  .active-menu {
    visibility: visible;
    opacity: 1;
  }
}
</style>

// @uportal/esco-content-menu-lit/src/hamburger-menu.ts
/*Lit */
import { html, LitElement, css, unsafeCSS, TemplateResult } from 'lit';
import { customElement, property, state } from 'lit/decorators.js';
import { classMap } from 'lit/directives/class-map.js';
/*SCSS*/
import HamburgerMenuScss from '@styles/hamburger-menu.scss';
/*Mixins*/
import { LitLoggable } from '@mixins/litLoggable';
/*Helpers*/
import sizeHelper from '@helpers/sizeHelper';
/*Components*/
import './content-menu';

@customElement('esco-hamburger-menu')
export class HamburgerMenu extends LitLoggable(LitElement) {
  @property({ type: Array })
  messages = [];
  @property({
    type: String,
    hasChanged(newVal: string) {
      return sizeHelper.validate(newVal, true, true);
    },
    attribute: 'favorites-portlet-card-size',
  })
  favoritesPortletCardSize = 'small';
  @property({
    type: String,
    hasChanged(newVal: string) {
      return sizeHelper.validate(newVal, true, true);
    },
    attribute: 'grid-portlet-card-size',
  })
  gridPortletCardSize = 'medium';
  @property({ type: String, attribute: 'default-org-logo' })
  defaultOrgLogo = '';
  @property({ type: String, attribute: 'force-org-logo' })
  forceOrgLogo = '';
  @property({ type: String, attribute: 'context-api-url' })
  contextApiUrl = process.env.APP_PORTAL_CONTEXT ?? '';
  @property({ type: String, attribute: 'favorite-api-url' })
  favoriteApiUrl =
    (process.env.APP_PORTAL_CONTEXT ?? '') +
    (process.env.APP_FAVORITES_PORTLETS_URI ?? '');
  @property({ type: String, attribute: 'layout-api-url' })
  layoutApiUrl =
    (process.env.APP_PORTAL_CONTEXT ?? '') +
    (process.env.APP_FAVORITES_URI ?? '');
  @property({ type: String, attribute: 'portlet-api-url' })
  portletApiUrl =
    (process.env.APP_PORTAL_CONTEXT ?? '') +
    (process.env.APP_BROWSABLE_PORTLETS_URI ?? '');
  @property({ type: String, attribute: 'organization-api-url' })
  organizationApiUrl = '';
  @property({ type: String, attribute: 'user-info-api-url' })
  userInfoApiUrl =
    (process.env.APP_PORTAL_CONTEXT ?? '') +
    (process.env.APP_USER_INFO_URI ?? '');
  @property({ type: String, attribute: 'sign-out-url' })
  signoutUrl = process.env.APP_LOGOUT_URL ?? '';
  @property({ type: String, attribute: 'user-info-portlet-url' })
  userInfoPortletUrl = '';
  @property({ type: String, attribute: 'switch-org-portlet-url' })
  switchOrgPortletUrl = '';
  @property({ type: String, attribute: 'user-org-id-attribute-name' })
  orgAttributeName = 'ESCOSIRENCourant[0]';
  @property({ type: String, attribute: 'org-logo-url-attribute-name' })
  orgLogoUrlAttributeName = 'otherAttributes.ESCOStructureLogo[0]';
  @property({ type: String, attribute: 'user-all-orgs-id-attribute-name' })
  userAllOrgsIdAttributeName = 'ESCOSIREN';
  @property({
    type: String,
    hasChanged(newVal: string) {
      return ['auto', 'always', 'never'].includes(newVal);
    },
    attribute: 'hide-action-mode',
  })
  hideActionMode = 'auto';
  @property({ type: Boolean, attribute: 'show-favorites-in-slider' })
  showFavoritesInSlider = false;
  @property({ type: Boolean })
  debug = false;

  @state()
  _isAppended = false;
  @state()
  _isVisible = false;

  constructor() {
    super();
    this.debugLog('Component loaded');
  }

  protected shouldUpdate(): boolean {
    if (this.defaultOrgLogo === '') {
      this.errorLog('default-org-logo attribute is required');
      return false;
    }
    return true;
  }

  toggleMenu(e: Event): void {
    e.preventDefault();
    this._isVisible = !this._isVisible;
    const html = document.querySelector('html');
    if (html) {
      html.style.overflowY = this._isVisible ? 'hidden' : 'auto';
    }
    const toggleEvt = new CustomEvent('toggle', {
      detail: {
        isVisible: this._isVisible,
      },
    });
    this.dispatchEvent(toggleEvt);
  }

  render(): TemplateResult {
    return html`
      <div class="hamburger-menu">
        <div
          class="content-menu-toggle"
          aria-label="Menu"
          role="button"
          title="Menu"
          aria-expanded="false"
          aria-haspopup="true"
          aria-controls="content-menu"
          @click=${this.toggleMenu}
        >
          <slot name="menu-icon">
            <div class="menu-wrapper">
              <div class="hm-line"></div>
              <div class="hm-line"></div>
              <div class="hm-line"></div>
            </div>
          </slot>
        </div>
        ${this._isVisible
          ? html`
              <div>
                <slot name="menu-content">
                  <esco-content-menu
                    class="${classMap({
                      'active-menu': this._isVisible,
                    })}"
                    context-api-url="${this.contextApiUrl}"
                    ?debug="${this.debug}"
                    default-org-logo="${this.defaultOrgLogo}"
                    favorite-api-url="${this.favoriteApiUrl}"
                    favorites-portlet-card-size="${this
                      .favoritesPortletCardSize}"
                    force-org-logo="${this.forceOrgLogo}"
                    grid-portlet-card-size="${this.gridPortletCardSize}"
                    hide-action-mode="${this.hideActionMode}"
                    ?is-hidden="${!this._isVisible}"
                    layout-api-url="${this.layoutApiUrl}"
                    .messages="${this.messages}"
                    organization-api-url="${this.organizationApiUrl}"
                    org-logo-url-attribute-name="${this
                      .orgLogoUrlAttributeName}"
                    portlet-api-url="${this.portletApiUrl}"
                    sign-out-url="${this.signoutUrl}"
                    ?show-favorites-in-slider="${this.showFavoritesInSlider}"
                    switch-org-portlet-url="${this.switchOrgPortletUrl}"
                    user-org-id-attribute-name="${this.orgAttributeName}"
                    user-all-orgs-id-attribute-name="${this
                      .userAllOrgsIdAttributeName}"
                    user-info-api-url="${this.userInfoApiUrl}"
                    user-info-portlet-url="${this.userInfoPortletUrl}"
                    @close=${this.toggleMenu.bind(this)}
                    ?fake-attribute="${true}"
                  ></esco-content-menu>
                </slot>
              </div>
            `
          : html``}
      </div>
    `;
  }
  static styles = [
    css`
      ${unsafeCSS(HamburgerMenuScss)}
    `,
  ];
}
