// @uportal/esco-content-menu/src/components/PortletCard.vue
<template>
  <div :class="mainClass">
    <div class="portlet-card-icon">
      <div
        v-if="iconUrl !== null"
        :style="'background-color:' + iconBackgroundColor"
        class="img-wrapper">
        <img
          :src="iconUrl"
          :alt="title">
      </div>
      <div
        v-else
        :style="'background-color:' + iconBackgroundColor"
        class="img-wrapper" />
    </div>
    <div class="portlet-card-title">
      {{ title }}
    </div>
    <div class="portlet-card-description">
      <ellipsis
        v-if="append"
        :message="truncate(description)"
        :line-height="'20px'"
        :end-char="'...'" />
    </div>
    <div
      v-if="!hideAction"
      class="portlet-card-action">
      <action-favorites
        v-if="canFavorite"
        :fname="fname"
        :chan-id="channelId"
        :is-favorite="isFavorite"
        :call-on-toggle-fav="callAfterAction"
        :favorite-api-url="favoriteApiUrl"
        :user-info-api-url="userInfoApiUrl"
        :back-ground-is-dark="favBgIsDark"
        :debug="debug" />
    </div>
  </div>
</template>

<script>
import Ellipsis from './Ellipsis';
import ActionFavorites from './ActionFavorites';
import {sizeValidator} from '../services/sizeTools';
import computeUrl from '../services/computeUrl';

export default {
  name: 'PortletCard',
  components: {
    ActionFavorites,
    Ellipsis,
  },
  props: {
    callAfterAction: {type: Function, default: () => {}},
    cssClass: {type: String, default: 'portlet-card'},
    // Background is needed if your icons doesn't have it integrated
    iconBackgroundColor: {type: String, default: 'Transparent'},
    isFavorite: {type: Boolean, default: false},
    favoriteApiUrl: {
      type: String,
      default:
        process.env.VUE_APP_PORTAL_CONTEXT +
        process.env.VUE_APP_FAVORITES_PORTLETS_URI,
    },
    userInfoApiUrl: {
      type: String,
      default:
        process.env.VUE_APP_PORTAL_CONTEXT + process.env.VUE_APP_USER_INFO_URI,
    },
    debug: {type: Boolean, default: false},
    size: {
      validator: sizeValidator(),
      default: 'medium',
    },
    hideAction: {type: Boolean, default: false},
    portletDesc: {type: Object, required: true},
    backGroundIsDark: {type: Boolean, default: false},
  },
  data() {
    return {
      fname: this.portletDesc.fname,
      channelId: this.portletDesc.id,
      description: this.portletDesc.description,
      title: this.portletDesc.title,
      canFavorite: this.portletDesc?.canAdd ? this.portletDesc.canAdd : true,
      iconUrl: computeUrl(
        this.portletDesc.parameters?.iconUrl?.value
          ? this.portletDesc.parameters?.iconUrl?.value
          : null
      ),
      append: false,
    };
  },
  mounted() {
    this.$nextTick(function() {
      this.append = true;
    });
  },
  computed: {
    mainClass() {
      let appClasses = [];
      appClasses.push(this.cssClass);
      appClasses.push(this.fname);

      if (this.portletDesc && this.portletDesc.categories) {
        appClasses = appClasses.concat(this.portletDesc.categories);
      }

      appClasses.push(this.size + '-card');

      if (this.backGroundIsDark) {
        appClasses.push('background-dark');
      }

      if (this.hideAction) {
        appClasses.push('hide-action');
      }

      return appClasses.map((v) => v.toLowerCase()).join(' ');
    },
    favBgIsDark() {
      return this.backGroundIsDark && this.size.includes('small');
    },
  },
  methods: {
    truncate(entry) {
      if (entry) {
        const text = entry.split('   ');
        return text[0].trim();
      }
      return entry;
    },
  },
};
</script>


<!-- Add "scoped" attribute to limit CSS to this component only -->
<style lang="scss" scoped>
@import './../styles/vars.scss';

.portlet-card {
  width: $PortletCardSizeLarge;
  height: 170px;
  padding: 5px;
  line-height: 20px;
  background-color: white;
  text-align: center;
  border-radius: 5px;
  position: relative;
  display: flex;
  flex-flow: column nowrap;

  /* prettier-ignore */
  box-shadow:
    0 2px 2px 0 rgba(0, 0, 0, 0.14),
    0 3px 1px -2px rgba(0, 0, 0, 0.12),
    0 1px 5px 0 rgba(0, 0, 0, 0.2);
  transition: box-shadow 0.25s;

  &:hover {
    cursor: pointer;

    /* prettier-ignore */
    box-shadow:
      0 7px 8px -4px rgba(0, 0, 0, 0.2),
      0 12px 17px 2px rgba(0, 0, 0, 0.14),
      0 5px 22px 4px rgba(0, 0, 0, 0.12);
  }

  > .portlet-card-icon,
  > .portlet-card-title,
  > .portlet-card-description {
    display: block;
    text-align: center;
    color: rgba(0, 0, 0, 0.8);
  }

  > .portlet-card-action {
    color: rgba(0, 0, 0, 0.34);
    position: absolute;
    top: 0;
    right: 0;
    margin: 5px;
  }

  > .portlet-card-icon {
    > div {
      display: inline-flex;
      align-items: center;
      justify-content: center;
      height: 83px;
      width: 83px;
      margin-top: -30px;
      border-radius: 10px;

      img {
        height: 100%;
        width: auto;
        border-radius: 10px;
      }
    }
  }

  > .portlet-card-title {
    padding-top: 1em;
    font-size: 16px;
    font-weight: bold;
    overflow: hidden;
    text-overflow: ellipsis;
  }

  > .portlet-card-description {
    padding-top: 0.3em;
    flex: 1;
    font-size: 14px;
  }

  &.medium-card,
  &.small-card,
  &.smaller-card {
    height: 160px;

    > .portlet-card-icon {
      > div {
        height: 75px;
        width: 75px;
      }
    }
  }

  &.small-card,
  &.smaller-card {
    height: auto;
    background-color: transparent;
    border: none;
    box-shadow: none;
    padding: 0;

    &.background-dark {
      > .portlet-card-title,
      > .portlet-card-description {
        color: white;
      }
    }

    > .portlet-card-description {
      display: none;
    }

    > .portlet-card-icon {
      > div {
        margin: 0;
      }
    }

    > .portlet-card-title {
      padding-top: 0.8em;
      font-weight: 500;
    }

    > .portlet-card-action {
      margin: 0;
    }

    &:not(.hide-action) {
      margin-top: $PortletCardButtonSize / 2;

      > .portlet-card-action {
        top: $PortletCardButtonSize - (($PortletCardButtonSize / 2) * 3);
      }
    }
  }

  &.medium-card {
    width: $PortletCardSizeMedium;
  }

  &.small-card {
    width: $PortletCardSizeSmall;
  }

  &.smaller-card {
    width: $PortletCardSizeSmaller;
  }
}
</style>

// @uportal/esco-content-menu-lit/src/portlet-card.ts
/*Lit*/
import { html, LitElement, css, unsafeCSS, TemplateResult } from 'lit';
import { customElement, property, state } from 'lit/decorators.js';
import { classMap } from 'lit/directives/class-map.js';
import { styleMap } from 'lit/directives/style-map.js';
/*SCSS*/
import PortletCardScss from '@styles/portlet-card.scss';
/*Mixins*/
import { LitLoggable } from '@mixins/litLoggable';
/*Helpers*/
import sizeHelper from '@helpers/sizeHelper';
import pathHelper from '@helpers/pathHelper';
import textHelper from '@helpers/textHelper';
/*Components*/
import './lit-ellipsis';
import './action-favorites';

@customElement('esco-portlet-card')
export class PortletCard extends LitLoggable(LitElement) {
  @property({ type: Array })
  messages = [];
  @property({ type: Object, attribute: 'portlet-desc' })
  portletDesc: Portlet | undefined;
  @property({ type: String, attribute: 'css-class' })
  cssClass = 'portlet-card';
  @property({ type: String, attribute: 'icon-background-color' })
  iconBackgroundColor = 'transparent';
  @property({
    type: String,
    hasChanged(newVal: string) {
      return sizeHelper.validate(newVal, true, true);
    },
  })
  size = 'medium';
  @property({ type: String, attribute: 'card-hover-src' })
  cardHoverSrc = 'none';
  @property({ type: Boolean, attribute: 'background-is-dark' })
  backgroundIsDark = false;
  @property({ type: Boolean, attribute: 'is-favorite' })
  isFavorite = false;
  @property({ type: Boolean, attribute: 'hide-action' })
  hideAction = false;
  @property({ type: Boolean })
  debug = false;

  @state()
  dataIsParsed = false;

  private fname = '';
  private chanId = 0;
  private pTitle = '';
  private description = '';
  private portletTitle = '';
  private canFavorite = false;
  private iconUrl = '';

  willUpdate(changedProperties: Map<string | number | symbol, unknown>): void {
    if (changedProperties.has('portletDesc')) {
      this.parseDesc();
      this.debugLog('portletDesc update', this.portletDesc);
    }
  }

  firstUpdated(): void {
    this.setLogIdentifier(this.fname);
    this.debugLog('First update', this);
  }

  parseDesc(): void {
    if (this.portletDesc !== undefined) {
      this.fname = this.portletDesc?.fname ?? '';
      this.chanId = this.portletDesc?.id ?? 0;
      this.pTitle = this.portletDesc?.title ?? '';
      this.description = this.portletDesc?.description ?? '';
      this.portletTitle = this.portletDesc?.title ?? '';
      this.canFavorite = this.portletDesc?.canAdd
        ? this.portletDesc.canAdd
        : true;
      this.iconUrl = this.portletDesc.parameters?.iconUrl?.value
        ? pathHelper.getUrl(this.portletDesc.parameters.iconUrl.value)
        : '';
      this.dataIsParsed = true;
    }
  }

  getHoverText(): string {
    switch (this.cardHoverSrc) {
      case 'title':
        return this.pTitle;
      case 'desc':
      case 'description':
        return this.description;
      default:
        return '';
    }
  }

  toggleFavorite(e: CustomEvent): void {
    const toggleEvt = new CustomEvent('toggle-favorite', {
      detail: e.detail,
    });
    this.dispatchEvent(toggleEvt);
  }

  render(): TemplateResult {
    const appClasses = {
      [this.cssClass.toLowerCase()]: true,
      [textHelper.sanitize(this.fname.toLowerCase())]: true,
      [this.size.toLowerCase() + '-card']: true,
      'background-dark': this.backgroundIsDark,
      'hide-action': this.hideAction,
    };
    if (this.portletDesc && this.portletDesc.categories)
      this.portletDesc.categories.forEach((cat: string) => {
        const sanCat = textHelper.sanitize(cat);
        appClasses[sanCat] = true;
      });

    return html`
      <div class="${classMap(appClasses)}" title="${this.getHoverText()}">
        <div class="portlet-card-icon">${this.renderIcon()}</div>
        <div class="portlet-card-title">${this.portletTitle}</div>
        <div class="portlet-card-description">${this.renderEllipsis()}</div>
        ${this.renderActionFavorites()}
      </div>
    `;
  }

  renderIcon(): TemplateResult {
    const style = {
      'background-color': this.iconBackgroundColor,
    };
    const img = html`<img src="${this.iconUrl}" alt="${this.portletTitle}" />`;
    return html`
      <div style=${styleMap(style)} class="img-wrapper">
        ${this.iconUrl
          ? img
          : html`<div class="defaultIcon">
              <p>${textHelper.getAcronym(this.fname)}</p>
            </div>`}
      </div>
    `;
  }

  renderEllipsis(): TemplateResult {
    if (this.dataIsParsed) {
      return html`
        <lit-ellipsis
          message="${textHelper.truncate(this.description)}"
          line-height="20px"
          end-char="..."
        ></lit-ellipsis>
      `;
    } else {
      return html``;
    }
  }

  renderActionFavorites(): TemplateResult {
    let returnHTML = html``;
    let afHTML = html``;
    if (this.canFavorite) {
      afHTML = html`
        <esco-action-favorites
          .messages="${this.messages}"
          fname="${this.fname}"
          chan-id="${this.chanId}"
          .isFavorite="${this.isFavorite}"
          ?background-is-dark="${this.backgroundIsDark}"
          ?debug="${this.debug}"
          @toggle=${this.toggleFavorite}
        /></esco-action-favorites>
      `;
    }
    if (!this.hideAction) {
      returnHTML = html`<div class="portlet-card-action">${afHTML}</div> `;
    }
    return returnHTML;
  }

  static styles = css`
    ${unsafeCSS(PortletCardScss)}
  `;
}
